### ISSUE TITLE
describe.each and test.each are shown as 'test result not found'

### ISSUE THREAD

**Issue by lampewebdev** [vitest-dev/vscode#7]
Hello,

when usuing `.each` the extension can not find the tests.

<img width="2136" alt="image" src="https://user-images.githubusercontent.com/44268468/160782371-699e7f05-a353-42fc-b146-d5e147e97805.png">
<img width="1477" alt="image" src="https://user-images.githubusercontent.com/44268468/160782549-ed7b3590-d25d-4d63-aef7-742f32e465d9.png">

**Comment by zxch3n** [comment]
`.each` is not supported yet. I'll find a way to make it work

**Comment by lampewebdev** [comment]
@zxch3n thanks for the info.

Are you accepting PR's?

If you could just point me to the right file, I could take a look at it :)

**Comment by zxch3n** [comment]
PRs are welcome! But I'm afraid this might not be an easy fix. Because we cannot infer the dynamic test name with 100% correctness from the static text content (which is how this plugin works right now). 

There are two options left

- Only register the dynamic tests' ancestors, and aggregate the test results to them
- Start a Vitest server and communicate with it

I'll work on the latter in a week or two, which can also provide watch mode #4 

If you are interested you can take a look at `discover.ts` and the VSCode testing API document.

**Comment by sheremet-va** [comment]
> * Start a Vitest server and communicate with it

Yeah, I think Vitest has an api to communicate with `--ui`? Can you use that?

**Comment by Nisgrak** [comment]
Maybe this is working now? In my repo the test shows the actual results

**Comment by watonyweng** [comment]
Hi @lampewebdev, the latest version of `vitest` already supports `describe.each` and `test.each`, does the test command still prompt `test result not found`?

**Comment by unikitty37** [comment]
Using the example from the [describe.each documentation](https://vitest.dev/api/#describe-each), I'm still only seeing placeholders rather than the expanded tests.

![image](https://user-images.githubusercontent.com/139183/225040561-a04d577b-e50c-4f4b-8ab1-0dad356a8be1.png)

Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:48:08.231Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

Vitest extension v0.2.39

**Comment by wadefletch** [comment]
+1

**Comment by dreamorosi** [comment]
In my case the `it.each` tests are running and being detected fine however all the ones afterwards fail/hang.

Would be great to find a way to either support the feature or find a compromise that at least allows to "skip" the test cases containing `.each` while making the rest of the suites running and being detected normally.

**Comment by langaads** [comment]
Similar to @dreamorosi i'm trying to use describe.each, it works fince once, and hangs afterwards.

Playing around, modifying, saving, stop/start watch, eventually unhangs it and it works well again.

i was able to capture this output

![image](https://github.com/vitest-dev/vscode/assets/13821505/4d068992-21c4-4ae4-ac2d-0c1b5c3e10a7)

**Comment by langaads** [comment]
I was able to make it work consistenly without hanging by prefixing the describe with "%s"

My guess is that the extension hangs if multiple describes with the same title are found, by adding the %s each describe becomes unique and it works.

![image](https://github.com/vitest-dev/vscode/assets/13821505/80774705-e01b-4668-835a-b3bb057a5dce)

**Comment by dreamorosi** [comment]
In my case, I'm using the each for `it` instead of `describe`.

If I do like suggested by @langaads, now the extension skips the tests entirely.

For reference, this is my test before the change suggested (it hangs):

```ts
describe('getRequestPaths', () => {
  it.each([['point', { type: 'point' }], ['range', { type: 'range' }]])(
    'it creates the correct request path',
    async ({ type }) => {
      // do thests
    }
  );
});
```

this is my test applying the suggestion (it skips it):

```ts
describe('getRequestPaths', () => {
  it.each([['point', { type: 'point' }], ['range', { type: 'range' }]])(
    'it creates the correct request path for %s',
    async (name, { type }) => {
      // do thests
    }
  );
});
```

![image](https://github.com/vitest-dev/vscode/assets/7353869/5b0d0e81-0b64-4586-ac18-6cb7501edfab)

**Comment by langaads** [comment]
There is a gotcha. 
If the first iteraction of the ".each" succeeds but the others don't, the extension will mark tests as passed and won't highlight failures. The footer still points that a test failed but the test results won't.

**Comment by vovsemenv** [comment]
Still getting this errors 😢

**Comment by sheremet-va** [comment]
This is now supported in 0.5.0 and higher. Note that the extension now requires Vitest 1.4.0 or higher.
